import { StyleSheet } from "react-native";
import { BorderRadius, Colors, FontSize, Spacing } from "@/constants/theme";

export const tourQueryFormStyles = StyleSheet.create({
  inquiryRoomBanner: {
    backgroundColor: "#f0f9ff",
    borderColor: "#bae6fd",
    borderWidth: 1,
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    marginBottom: Spacing.md,
  },
  applyRoomsBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: "#0284c7",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: BorderRadius.md,
    alignSelf: "flex-start",
  },
  applyRoomsBtnText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 12,
  },
  label: {
    fontSize: FontSize.xs,
    color: Colors.textTertiary,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    marginTop: Spacing.md,
    marginBottom: 4,
  },
  input: {
    backgroundColor: Colors.surface,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.md,
    fontSize: FontSize.md,
    color: Colors.text,
  },
  textarea: { minHeight: 90, textAlignVertical: "top" },
  flexField: { flex: 1 },
  row2: { flexDirection: "row", gap: Spacing.md },
  row3: { flexDirection: "row", gap: Spacing.sm },
  help: { color: Colors.textTertiary, fontSize: FontSize.xs, marginTop: 4 },
  helpErr: { color: Colors.error, fontSize: FontSize.xs, marginTop: 4 },
  policyWrap: { gap: Spacing.sm, marginBottom: Spacing.sm },
  policyCard: {
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.borderSubtle,
    backgroundColor: Colors.surface,
    overflow: "hidden",
  },
  policyTap: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    padding: Spacing.md,
  },
  policyTapTitle: { flex: 1, fontSize: FontSize.sm, fontWeight: "800", color: Colors.text },
  policyTapHint: { fontSize: FontSize.xs, fontWeight: "700", color: Colors.textTertiary },
  policyTextarea: { minHeight: 120, marginHorizontal: Spacing.md, marginBottom: Spacing.md },
  pickerBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: Colors.surface,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.md,
    minHeight: 48,
  },
  pickerBtnDisabled: { opacity: 0.5, backgroundColor: Colors.surfaceAlt },
  pickerBtnText: { flex: 1, fontSize: FontSize.md, color: Colors.text, fontWeight: "600" },
  pickerBtnTextDisabled: { color: Colors.textTertiary },
  variantsContainer: { gap: Spacing.sm, marginTop: Spacing.sm },
  variantRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Spacing.sm,
  },
  variantCheckboxContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  variantLabel: { flex: 1, fontSize: FontSize.sm, fontWeight: "700", color: Colors.text },
  applyHotelsBtn: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.primarySoft,
    borderWidth: 1,
    borderColor: Colors.primaryLight,
  },
  applyHotelsBtnText: { fontSize: FontSize.xs, fontWeight: "800", color: Colors.primary },
  itineraryHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Spacing.md,
    marginTop: 4,
  },
  addDayBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.primarySoft,
    borderWidth: 1,
    borderColor: Colors.primaryLight,
  },
  addDayBtnText: {
    fontSize: FontSize.xs,
    fontWeight: "800",
    color: Colors.primary,
  },
  emptyItineraryWrap: {
    padding: Spacing.md,
    borderRadius: BorderRadius.lg,
    backgroundColor: Colors.surfaceAlt,
    marginTop: Spacing.sm,
  },
  dayCard: {
    backgroundColor: Colors.surface,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.borderSubtle,
    padding: Spacing.md,
    marginTop: Spacing.md,
  },
  dayHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: Spacing.sm,
  },
  dayLabel: {
    fontSize: FontSize.sm,
    fontWeight: "900",
    color: Colors.primary,
  },
  deleteDayBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  deleteDayText: { fontSize: FontSize.xs, fontWeight: "700", color: Colors.error },
  inlineToggle: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: Spacing.sm,
    marginBottom: Spacing.xs,
  },
  inlineToggleText: {
    fontSize: FontSize.xs,
    fontWeight: "800",
    color: Colors.primary,
  },
  allocationsHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: Spacing.md,
    marginBottom: Spacing.sm,
  },
  allocationsTitle: {
    fontSize: FontSize.xs,
    fontWeight: "900",
    color: Colors.textTertiary,
    textTransform: "uppercase",
  },
  addRoomBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.primarySoft,
  },
  addRoomBtnText: { fontSize: FontSize.xs, fontWeight: "800", color: Colors.primary },
  noRoomsText: { fontSize: FontSize.xs, color: Colors.textTertiary, fontStyle: "italic" },
  roomCard: {
    backgroundColor: Colors.surfaceAlt,
    borderRadius: BorderRadius.md,
    padding: Spacing.sm,
    marginTop: Spacing.sm,
    gap: Spacing.sm,
  },
  roomCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  roomLabel: { fontSize: FontSize.xs, fontWeight: "900", color: Colors.textSecondary },
  deleteRoomBtn: { padding: 4 },
  roomFieldLabel: {
    fontSize: 10,
    fontWeight: "800",
    color: Colors.textTertiary,
    textTransform: "uppercase",
    marginBottom: 4,
  },
  roomPickerBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: Colors.surface,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: Colors.borderSubtle,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 10,
    minHeight: 40,
  },
  roomPickerText: { flex: 1, fontSize: FontSize.sm, fontWeight: "600", color: Colors.text },
  quantityInput: {
    backgroundColor: Colors.surface,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: Colors.borderSubtle,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 10,
    fontSize: FontSize.md,
    fontWeight: "700",
    color: Colors.text,
    textAlign: "center",
  },
  customRoomField: { marginTop: Spacing.xs },
  customRoomInput: {
    backgroundColor: Colors.surface,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: Colors.borderSubtle,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 10,
    fontSize: FontSize.sm,
    color: Colors.text,
  },
  webLinkBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
    marginTop: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  webLinkText: {
    fontSize: FontSize.sm,
    fontWeight: "700",
    color: Colors.primary,
  },
  tabBadge: {
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: Colors.error,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
    marginLeft: 4,
  },
  tabBadgeText: {
    color: "#fff",
    fontSize: 9,
    fontWeight: "900",
  },
  errorBanner: {
    marginHorizontal: Spacing.lg,
    marginBottom: Spacing.sm,
    padding: Spacing.md,
    borderRadius: BorderRadius.md,
    backgroundColor: "#fef2f2",
    borderWidth: 1,
    borderColor: "#fecaca",
  },
  errorBannerText: {
    fontSize: FontSize.sm,
    color: "#b91c1c",
    fontWeight: "600",
  },
});
